POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "username": "ali",
    "password": "ali"
}

###

POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "username": "ali",
    "password": "ali"
}

###

POST http://localhost:3000/api/auth/refreshToken
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIwYjc4NWE4NDQ1YzAzZDMyMjE0N2IiLCJ0b2tlbklkIjoiNjYyMGI3ODVhODQ0NWMwM2QzMjIxNDdjIiwiaWF0IjoxNzEzNDIwMTY1LCJleHAiOjE3MTYwMTIxNjV9.-gXIDqB0rN5lc1VnquRysatdUVmHaslrNgz1QHjwFfw"
}

###

POST http://localhost:3000/api/auth/accessToken
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIwYjEzNmIyNWE3ODlmNTUwMzY1MTIiLCJ0b2tlbklkIjoiNjYyMGRkYjlhNTNhZGM1ZmFkODMwNGEyIiwiaWF0IjoxNzEzNDI5OTQ2LCJleHAiOjE3MTYwMjE5NDZ9.rh6pL_XBWZjtITK7-wDhDYGa1dQUxrppHEx0FpXV4l8"
}


###

POST http://localhost:3000/api/auth/logout
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM3Yjg3N2Q0NjNjOTQ3YTJiOTU4OGIiLCJ0b2tlbklkIjoiNjYzN2I4NzdkNDYzYzk0N2EyYjk1ODhjIiwiaWF0IjoxNzE0OTI3NzM1LCJleHAiOjE3MTc1MTk3MzV9.6V5plG72edMmRyVEfSEjVH-jMbkW2Hg_l7JoyIMzcgM"
}

###

GET http://localhost:3000/api/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM3Yjk3ZjRkODAzYmM5ZDQwMjIwNWQiLCJpYXQiOjE3MTQ5MzE2NjgsImV4cCI6MTcxNDkzMjI2OH0.VM75gGruC-TGE72VPTnNIQAVnZUwMLXQnpgbVYi4Om0


