POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "username": "saad",
    "password": "saad"
}

###

POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "username": "SAAD AMIR",
    "password": "123saad"
}

###

POST http://localhost:3000/api/auth/refreshToken
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIwYjc4NWE4NDQ1YzAzZDMyMjE0N2IiLCJ0b2tlbklkIjoiNjYyMGI3ODVhODQ0NWMwM2QzMjIxNDdjIiwiaWF0IjoxNzEzNDIwMTY1LCJleHAiOjE3MTYwMTIxNjV9.-gXIDqB0rN5lc1VnquRysatdUVmHaslrNgz1QHjwFfw"
}

###

POST http://localhost:3000/api/auth/accessToken
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIwYjEzNmIyNWE3ODlmNTUwMzY1MTIiLCJ0b2tlbklkIjoiNjYyMGRkYjlhNTNhZGM1ZmFkODMwNGEyIiwiaWF0IjoxNzEzNDI5OTQ2LCJleHAiOjE3MTYwMjE5NDZ9.rh6pL_XBWZjtITK7-wDhDYGa1dQUxrppHEx0FpXV4l8"
}


###

POST http://localhost:3000/api/auth/logout
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjIwZTg3Njk2ZmJiOWViYmM0YjBmMzUiLCJ0b2tlbklkIjoiNjYyMGU4NzY5NmZiYjllYmJjNGIwZjM2IiwiaWF0IjoxNzEzNDMyNjk1LCJleHAiOjE3MTYwMjQ2OTV9.wgZde_n4ABaElznWulssIj28bl9NAu62ouk2_WbyHFU"
}

###

GET http://localhost:3000/api/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM2YWM1NDFjNDQ4ODZkNzBmYzk5OTQiLCJ0b2tlbklkIjoiNjYzNmI1Y2YwMDliMWZkYjUwYmFiMGNlIiwiaWF0IjoxNzE0ODYxNTE5LCJleHAiOjE3MTc0NTM1MTl9.6DdTCnOPWTZ60tzRrv4kcdLZz7yRBbyD-t7n9pMPUow

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM2YWM1NDFjNDQ4ODZkNzBmYzk5OTQiLCJ0b2tlbklkIjoiNjYzNmI1Y2YwMDliMWZkYjUwYmFiMGNlIiwiaWF0IjoxNzE0ODYxNTE5LCJleHAiOjE3MTc0NTM1MTl9.6DdTCnOPWTZ60tzRrv4kcdLZz7yRBbyD-t7n9pMPUow"
}
